#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

/home/ali/.config/polybar/launch.sh

BLUE="#42A5F5"
RED="#EC7875"
YELLOW="#FDD835"
GREEN="#61C766"
MAGENTA="#BA68C8"

bspc config border_width         1
bspc config top_padding          17
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspwm colors
bspc config normal_border_color         "#4c566a"
bspc config active_border_color         "#1e1e1e"
bspc config focused_border_color        "#FF6C6B"
bspc config presel_feedback_color       "#5e81ac"
bspc config urgent_border_color         "#dd2727"

bspc rule -a Brave desktop='^2'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a PacketTracer state=floating

# Auto Start

# picom
picom &

# nitrogen
nitrogen --restore &

# cursor
xsetroot -cursor_name left_ptr

# xsecurelock
xss-lock xsecurelock &
